### PR TITLE
rename logos

### PR DESCRIPTION
**Pull request by soerenmartius**
# Changelog
Renamed logos and fixed typo.
Breaking change: all repositories that reference to `https://raw.githubusercontent.com/mineiros-io/brand/master/mineiros-vertial-logo-smaller-font.svg` should replace the reference with `https://raw.githubusercontent.com/mineiros-io/brand/master/mineiros-vertical-logo.svg`

### CODE REVIEW

**Comment by mariux** [comment]
can we keep the broken one fo 2 weeks so not to force upgrade right away? @soerenmartius

**Comment by soerenmartius** [comment]
> can we keep the broken one fo 2 weeks so not to force upgrade right away? @soerenmartius

yes sure - I am gonna open PRs for all repos to update the logo. We should only merge once we've got all PRs in place.

**Comment by mariux** [comment]
https://github.com/mineiros-io/brand/blob/rename-logos/mineiros-primary-logo-white-font.svg has brokne font.. (notpart of the PR)

can we have the logos not with transparent borders to make them square.... but have a square version and a non-square? what do you think?

**Comment by mariux** [comment]
> > can we keep the broken one fo 2 weeks so not to force upgrade right away? @soerenmartius
> 
> yes sure - I am gonna open PRs for all repos to update the logo. We should only merge once we've got all PRs in place.

i guess we should merge as we do not have the new logo in place already, or do we?

**Comment by mariux** [comment]
maybe it would be good to copy logos for usage so we just have to replavce it here to change all the logos in all the repos by replacing this file?  e.g. `function/github-repo-logo.svg`

**Comment by soerenmartius** [comment]
> > > can we keep the broken one fo 2 weeks so not to force upgrade right away? @soerenmartius
> > 
> > 
> > yes sure - I am gonna open PRs for all repos to update the logo. We should only merge once we've got all PRs in place.
> 
> i guess we should merge as we do not have the new logo in place already, or do we?

nope, PR's will update the references to https://github.com/mineiros-io/brand/blob/master/mineiros-vertical-logo.svg which exists already but will be overwritten with an aligned version with this PR.

**Comment by soerenmartius** [comment]
> maybe it would be good to copy logos for usage so we just have to replavce it here to change all the logos in all the repos by replacing this file? e.g. `function/github-repo-logo.svg`

Yeah, possibly. I would rather keep links for now though since this is working well also.

**Comment by soerenmartius** [comment]
> You actually forgot to update the README.md...
> 
> also not sure about the transparent borders... GitHub seems to cut them away... not sure this is true everywhere... but fine with it.. ;)

fixed in 
fdac6f1

**Pull request merged**
